### ISSUE TITLE
Support for ESP32 with Ethernet-Module?

### ISSUE THREAD

**Issue by kokospalme** [brunchboy/beat-carabiner#4]
Hello there,
Would it be possible to run this project on an ESP32, running for example [Espruino](https://www.espruino.com/)on the machine?
The goal would be to connect Ableton Link and xdj devices without running a computer. 

I already started an Arduino-project with an ESP32-C3(Singlecore 80Mhz) and a W5500(Ethernet) module connected over SPI just to play arround with the udp packages which were sent from Ableton and my other gear. Someone else already figured out some variables and made a ["cheatsheet"](https://github.com/westhom/AbletonLinkProtocol), but as I thought there is much more magic going on to synchronize at least the Ableton link devices with each other...

So before I make a deep dive into clojure I have a few questions:
* Is this project tied to a certain kind of hardware?
* how much work would it be to get this running on a microcontrollerboard/raspberryPi etc.?
* Is this even possible?

I would be very happy about your opinions, tips and assessments. 
Thank you

**Comment by brunchboy** [comment]
Hello, @kokospalme! For this kind of discussion, please use the [Zulip discussion stream](https://deep-symmetry.zulipchat.com/#narrow/stream/278354-carabiner) rather than opening issues against a project. The first challenge is going to be, which project are you actually interested in? This one, which involves both Carabiner and Beat Link, for coordinating with performances on Pioneer DJ professional equipment? Or just [lib-carabiner](https://github.com/Deep-Symmetry/lib-carabiner), which provides Java access to Carabiner independently of [Beat Link](https://github.com/Deep-Symmetry/beat-link#beat-link)? Or just [Carabiner](https://github.com/Deep-Symmetry/carabiner) directly, which provides a loose language-independent network interface to the Link library? Or even just raw [Ableton Link](https://www.ableton.com/en/link/) itself, which is used by Carabiner but is not a Deep Symmetry project, so you would want to talk to Ableton with your questions.

Carabiner [releases](https://github.com/Deep-Symmetry/carabiner/releases/tag/v1.1.6) are compiled for a variety of architectures, including the Raspberry Pi. So it is likely possible to compile it for your board, although we are unlikely to be able to offer much help for that. C++ is not a world in which we do regular development; that project was undertaken out of necessity and left alone as much as possible.

So, best of luck figuring out what you are trying to accomplish, and please do feel free to ask followup questions in the Zulip community in case someone can help you there!

**Comment by brunchboy** [comment]
Ah, I see you are already talking to Ableton. It seems like that is the most likely useful direction for you, because it looks like you are seeking a way to compile the Link library itself, not any of the layers on top of it that we offer.

**Comment by kokospalme** [comment]
Thank you for the quick reply! I just want to setup my gear so that my Akai force ( ableton link) talks to the XDJs. I thought the only way was to setup carabiner or open beat control on a computer, but I overlooked that this can be archieved with an raspberry pi, which ist quite nice :)

**Comment by brunchboy** [comment]
Indeed, that was the main reason I created Open Beat Control. These days, with the Pi 4, you can even use the full power of Beat Link Trigger, accessing the GUI over a VNC server. Please feel free to ask followup questions on Zulip as you explore your goals.
